import Head from 'next/head'
import PropTypes from 'prop-types'
import { SessionProvider } from 'next-auth/react'
import { reduxWrapper } from '@pimred/redux'
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import { io } from 'socket.io-client'

import Footer from '../components/containers/footer'
import Header from '../components/containers/header'
import { SocketProvider } from '../components/contexts/socketContext'
import { useRef } from 'react'
config.autoAddCss = false

const App = ({
  Component,
  pageProps: { session, ...pageProps }
}) => {
  const socket = useRef(io('http://localhost:5000/'))
  return (
    <SessionProvider session={session}>
      <SocketProvider value={socket.current}>
        <Header />
        <Component {...pageProps} />
        <Footer />
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
          <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC' crossOrigin='anonymous' />
          <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js' integrity='sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM' crossOrigin='anonymous' />
        </Head>
      </SocketProvider>
    </SessionProvider>
  )
}

App.propTypes = {
  Component : PropTypes.any,
  pageProps : PropTypes.object
}

export default reduxWrapper.withRedux(App)
